### ISSUE TITLE
Incorrect MotorVelFeedback translation

### ISSUE THREAD

**Issue by wisniax** [wisniax/raptor_ws#3]
The value seems to be incorrectly decoded or encoded...
![image](https://github.com/wisniax/raptor_ws/assets/101927988/9d259b37-0f4d-410c-85ea-3915d4795130)
The function trend is fine, but the value is not... The STM showed that it should be closer to 30-40 at peak - not 120...

![image](https://github.com/wisniax/raptor_ws/assets/101927988/1f17fec8-4546-4e9f-9db2-a347c899f845)
While it is not the exact same frame, it's close enough and the decoded value should be similar.

Anyhow here is all the data:
[idk_dalejTesty.zip](https://github.com/wisniax/raptor_ws/files/13864495/idk_dalejTesty.zip)

**Comment by wisniax** [comment]
When reviewing more data it does seem like the bit order is not correct:
![image](https://github.com/wisniax/raptor_ws/assets/101927988/32e67274-df61-4e91-bed0-51842cb3f69c)
The 3rd byte changes the most while by documentation it should be more significant than 2nd byte...
Aprox value for reference:
![image](https://github.com/wisniax/raptor_ws/assets/101927988/76c495a8-8372-4dcd-be70-c6d991412c10)

It is safe to note that new CM.h was **NOT** yet implemented in STM (Embedded system) and thus it might just be error present earlier that just so happened to work due to incorrect documentation interpretation, and was now highlighted by the rework.

Second opinion appreciated.

**Comment by AlvaroBajceps** [comment]
Bug confirmed.
https://github.com/wisniax/raptor_ws/blob/36b763af13fc5ba868e4b9851e5e9b313f18cb38/src/can_wrapper/include/CM/CM_Message.h#L21-L26

**Comment by AlvaroBajceps** [comment]
Using this test case (on branch [fix/3-incorrect-motorvelfeedback-translation](https://github.com/wisniax/raptor_ws/tree/fix/3-incorrect-motorvelfeedback-translation)):
```cpp
float rpm_scale = 128.0f;
uint8_t rawData[] = {0,0,0,0,0,75,15,0};

CM_CanMessage cm_test;

memset(&cm_test,0, sizeof(cm_test));
memcpy(cm_test.data.raw,rawData,8);

float rpm = CM_convert_GetMotorVel_mtor(
	rpm_scale,
	cm_test.data.get_motor_vel.motor_C_value,
	cm_test.data.get_motor_vel.motor_C_dir
);
```
(see [CM_convert_GetMotorVel_mtor](https://github.com/wisniax/raptor_ws/blob/4b0411295124f2e171a89e7fb7777cabfab2c615/src/can_wrapper/include/CM/CM_Functions.h#L98))
got us values:

```
cm_test.data.get_motor_vel.motor_C_value: 3915
cm_test.data.get_motor_vel.motor_C_dir: 0
rpm: 30.5859375
```
